apiVersion: v1
kind: ServiceAccount
metadata:
  name: hadron-controller
  namespace: hadron
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hadron-job-manager
  namespace: hadron
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hadron-controller-job-manager
  namespace: hadron
subjects:
  - kind: ServiceAccount
    name: hadron-controller
    namespace: hadron
roleRef:
  kind: Role
  name: hadron-job-manager
  apiGroup: rbac.authorization.k8s.io
